# Generated by Django 4.2.7 on 2023-12-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorProfileMngmnt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=20)),
                ('order_date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('quality_rating', models.FloatField(max_length=20)),
                ('issue_date', models.DateTimeField()),
                ('acknowledgement_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='vendorProfileMngmnt.vendor')),
            ],
        ),
    ]
