# Generated by Django 4.2.7 on 2023-12-03 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendorProfileMngmnt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField(max_length=20)),
                ('quality_rating_avg', models.FloatField(max_length=20)),
                ('average_response_time', models.FloatField(max_length=20)),
                ('fulfillment_rate', models.FloatField(max_length=20)),
                ('vendor', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='vendorProfileMngmnt.vendor')),
            ],
        ),
    ]
